#!/bin/bash
# Um ein php-Script im Debug-Modus zu starten
export XDEBUG_CONFIG="idekey=snitter"
/usr/local/bin/php "$@"

# Auf http://xdebug.org/docs/remote steht auch, wie man Apache-Scripte debugt, nämlich mittels ?XDEBUG_SESSION_START=[session_name]
# also für uns xdebug
